[package]
name = "rudo"
version = "1.0"
authors = ["0xCAP <0xCAP@mail.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.110", features = ["derive"] } 
serde_json = "1.0.53"
